services:
  # Ayush Intelligence Unified Platform
  - type: web
    name: icd-mapping-platform
    runtime: python
    region: singapore
    buildCommand: ./build.sh
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: PYTHONPATH
        value: "backend"
      - key: CORSMiddleware
        value: "*"
