services:
  # Backend API
  - type: web
    name: icd-mapping-backend
    runtime: python
    region: singapore
    buildCommand: ./build.sh
    startCommand: uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: PYTHONPATH
        value: "backend"
      - key: CORSMiddleware
        value: "*"

  # Frontend UI
  - type: web
    name: icd-mapping-frontend
    runtime: node
    region: singapore
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: icd-mapping-backend
          property: url
